
-- User table
insert into users(mail, password, first_name, last_name, phone_num) values ('20522122@gm.uit.edu.vn', '$2b$10$5c8sOgAuE59yKUpR9vEdCuI.fX..VAY/l/VyeaKunVJzhqc4y0OGS', 'Nguyễn', 'Tuấn', '0967781796');
insert into users(mail, password, first_name, last_name, phone_num) values ('20521366@gm.uit.edu.vn', '$2b$10$5c8sOgAuE59yKUpR9vEdCuI.fX..VAY/l/VyeaKunVJzhqc4y0OGS', 'Mai', 'Hưng', '0967781796');
insert into users(mail, password, first_name, last_name, phone_num) values ('20521760@gm.uit.edu.vn', '$2b$10$5c8sOgAuE59yKUpR9vEdCuI.fX..VAY/l/VyeaKunVJzhqc4y0OGS', 'Hoàng', 'Phúc', '0967781796');
insert into users(mail, password, first_name, last_name, phone_num) values ('20521480@gm.uit.edu.vn', '$2b$10$5c8sOgAuE59yKUpR9vEdCuI.fX..VAY/l/VyeaKunVJzhqc4y0OGS', 'Nguyễn', 'Khôi', '0961742715');
insert into users(mail, password, first_name, last_name, phone_num) values ('20521450@gm.uit.edu.vn', '$2b$10$5c8sOgAuE59yKUpR9vEdCuI.fX..VAY/l/VyeaKunVJzhqc4y0OGS', 'Nguyễn', 'Khanh', '0967781796');
insert into users(mail, password, first_name, last_name, phone_num) values ('20521565@gm.uit.edu.vn', '$2b$10$5c8sOgAuE59yKUpR9vEdCuI.fX..VAY/l/VyeaKunVJzhqc4y0OGS', 'Lữ', 'Long', '0967781796');

-- GroupTask table
insert into group_task(user_mail, name) values ('20522122@gm.uit.edu.vn', 'SE109');
insert into group_task(user_mail, name) values ('20522122@gm.uit.edu.vn', 'IE106');
insert into group_task(user_mail, name) values ('20522122@gm.uit.edu.vn', 'SE346');

-- Task table
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Mandy', 'Elizabeth City State University', '30/04/2023', '07/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Dusty', 'Tottori University', '29/04/2023', '10/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Patty', 'Sichuan Agricultural University', '02/05/2023', '08/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Ilysa', 'Centro Universitário Adventista de São Paulo', '26/04/2023', '05/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Candice', 'Smolny University', '25/04/2023', '09/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Fernandina', 'ITT Technical Institute Maitland', '29/04/2023', '09/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Wernher', 'Women''s University in Africa', '27/04/2023', '13/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Fee', 'Kandahar University', '01/05/2023', '14/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Cathrine', 'Marcus Oldham College', '29/04/2023', '09/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Greer', 'Lamphun College of Agriculture and Technology', '30/04/2023', '05/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Opal', 'Kyorin University', '27/04/2023', '08/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Elyse', 'University of Wisconsin - Eau Claire', '26/04/2023', '14/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Seymour', 'Charter Oak State College', '29/04/2023', '13/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Nerta', 'City University of New York, John Jay College of Criminal Justice', '25/04/2023', '13/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Griselda', 'High Institute for Banking & Financial Studies', '02/05/2023', '11/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Marchall', 'Vidyasagar University', '26/04/2023', '05/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Clarabelle', 'Isik University', '27/04/2023', '10/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Lennard', 'Tohoku Fukushi University', '30/04/2023', '06/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Byrom', 'Universitas Bengkulu', '01/05/2023', '05/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Monica', 'Czech University of Agriculture Prague', '29/04/2023', '13/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Eugen', 'Université de Montpellier I', '26/04/2023', '12/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Kelley', 'Maria Grzegorzewska College for Special Education', '03/05/2023', '10/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Dosi', 'Kyoto Institute of Technology', '27/04/2023', '07/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Kalinda', 'Université Val-de-Marne (Paris XII)', '27/04/2023', '12/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Sharia', 'Instituto Superior Politécnico José Antonio Echeverría', '27/04/2023', '09/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Hedy', 'Seberang Perai Polytechnic', '03/05/2023', '07/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Elton', 'Shandong Medical University', '28/04/2023', '06/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Weider', 'Fachhochschule Lippe', '27/04/2023', '13/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Malcolm', 'Kazan State University', '25/04/2023', '12/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Darbee', 'University of Kordofan', '26/04/2023', '07/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Martie', 'University of Lecce', '28/04/2023', '11/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Beverie', 'Ecole Normale Supérieure de Fontenay-Saint Cloud', '28/04/2023', '09/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Rorie', 'Mamasani University of Technology', '29/04/2023', '12/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Minna', 'Universidad de Pamplona', '28/04/2023', '11/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Nickey', 'Palm Beach State College', '28/04/2023', '05/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Aveline', 'Soran University', '27/04/2023', '11/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Fernandina', 'Fachhochschule Ravensburg-Weingarten', '30/04/2023', '11/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Royal', 'Bartlesville Wesleyan College', '30/04/2023', '14/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Calida', 'Ho Chi Minh City University of Architecture', '03/05/2023', '14/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Dieter', 'University of Florida', '03/05/2023', '09/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Fara', 'Texas A&M University - Galveston', '27/04/2023', '14/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Shelby', 'Universitas Madura', '02/05/2023', '07/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Helga', 'Dalian University of Technology', '29/04/2023', '06/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Benedicto', 'Ecole Supérieure de Chimie Physique Electronique de Lyon', '02/05/2023', '05/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Lois', 'Fort Hays State University', '28/04/2023', '11/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Karrah', 'Taipei Medical College', '26/04/2023', '12/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Cozmo', 'Walsh University', '03/05/2023', '11/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Garland', 'Maxim Gorky Institute of Literature', '03/05/2023', '05/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Trudy', 'Queen Mary and Westfield College, University of London', '28/04/2023', '05/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Piggy', 'Kaliningrad State Technical University', '25/04/2023', '08/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Peggie', 'Yanbian University', '28/04/2023', '11/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Etti', 'Myongji University', '27/04/2023', '08/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Erhart', 'National Technological University', '26/04/2023', '06/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Meryl', 'Saitama Medical School', '03/05/2023', '11/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Sharla', 'University of Genoa', '29/04/2023', '13/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Kamillah', 'Vaganova Academy of Russian Ballet', '29/04/2023', '08/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Erwin', 'University of Notre Dame', '27/04/2023', '08/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Norby', 'Kyoto Sangyo University', '30/04/2023', '14/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Tanhya', 'University of Science and Technology Beijing', '28/04/2023', '13/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Wendell', 'Mansoura University', '26/04/2023', '07/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Windy', 'Southampton Solent University', '28/04/2023', '13/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Stanley', 'University of Economics in Bratislava', '26/04/2023', '05/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Homerus', 'İstanbul Şehir University', '25/04/2023', '05/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Stu', 'University of Sri Jayawardenapura', '29/04/2023', '10/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Bancroft', 'Odessa State Medical University', '30/04/2023', '14/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Bret', 'Universidade do Vale do Itajaí', '01/05/2023', '11/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Brinn', 'Kaplan University', '28/04/2023', '07/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Dorothea', 'Academy of Economics in Poznan', '01/05/2023', '10/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Onfroi', 'South Valley University', '25/04/2023', '13/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Ingamar', 'Troy University, Dothan', '01/05/2023', '09/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Ron', 'Open International University for Alternative Medicines', '03/05/2023', '07/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Fred', 'Emory University', '27/04/2023', '06/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Eve', 'Academy of Economics in Cracow', '27/04/2023', '13/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Alidia', 'Universidad de Oriente', '29/04/2023', '11/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Grove', 'Russian-Armenian (Slavonic) State University', '01/05/2023', '06/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Olivette', 'Independent University, Bangladesh', '30/04/2023', '12/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Helaina', 'Espam Formation University', '30/04/2023', '12/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Cybill', 'National University of Science and Technology', '28/04/2023', '09/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Kory', 'Privredna Akademija (Business Academy)', '28/04/2023', '05/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Concettina', 'Shanghai Lixin University of Commerce', '03/05/2023', '12/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Ami', 'Universidad Champagnat', '27/04/2023', '08/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Dotty', 'American Conservatory Theater', '26/04/2023', '10/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Catharine', 'National Sun Yat-Sen University', '28/04/2023', '11/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Chantalle', 'William Tyndale College', '28/04/2023', '05/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Lowrance', 'Universidade Independente', '01/05/2023', '14/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Lexie', 'Sindh Madressatul Islam University', '02/05/2023', '10/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Josh', 'Université des Antilles et de la Guyane', '27/04/2023', '13/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Evelyn', 'Fachhochschule Vorarlberg', '02/05/2023', '08/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Silvio', 'North Kazakhstan State University', '03/05/2023', '06/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Gerrilee', 'Instituto Superior de Ciências Empresariais e de Turismo', '25/04/2023', '05/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Kori', 'Comenius University in Bratislava', '03/05/2023', '06/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Roxane', 'University of Rio Grande', '02/05/2023', '09/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Tammy', 'Kettering University (GMI)', '30/04/2023', '06/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Alyce', 'Tashkent State University of Oriental Studies ', '29/04/2023', '14/05/2023', true, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Noach', 'Military Institute of Science and Technology', '25/04/2023', '13/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Gwendolyn', 'University of Amsterdam', '01/05/2023', '10/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Biron', 'University of Calicut', '28/04/2023', '07/05/2023', false, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Robb', 'Universidade Gregorio Semedo', '29/04/2023', '06/05/2023', true, true);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Daloris', 'Technological University (Myitkyina) ', '01/05/2023', '10/05/2023', false, false);
insert into task (user_mail, title, description, from_date, to_date, is_completed, is_favorited) values ('20522122@gm.uit.edu.vn', 'Erin', 'Universidad de La Amazonia', '03/05/2023', '13/05/2023', true, true);

-- TaskIncluded table
insert into task_included(group_task_id, task_id) values (1, 1);
insert into task_included(group_task_id, task_id) values (2, 2);
insert into task_included(group_task_id, task_id) values (3, 3);
insert into task_included(group_task_id, task_id) values (1, 4);
insert into task_included(group_task_id, task_id) values (2, 5);
insert into task_included(group_task_id, task_id) values (3, 6);
insert into task_included(group_task_id, task_id) values (1, 7);
insert into task_included(group_task_id, task_id) values (2, 8);
insert into task_included(group_task_id, task_id) values (3, 9);
insert into task_included(group_task_id, task_id) values (1, 10);
insert into task_included(group_task_id, task_id) values (2, 11);
insert into task_included(group_task_id, task_id) values (3, 12);
insert into task_included(group_task_id, task_id) values (1, 13);
insert into task_included(group_task_id, task_id) values (2, 14);
insert into task_included(group_task_id, task_id) values (3, 15);
insert into task_included(group_task_id, task_id) values (1, 16);
insert into task_included(group_task_id, task_id) values (2, 17);
insert into task_included(group_task_id, task_id) values (3, 18);
insert into task_included(group_task_id, task_id) values (1, 19);
insert into task_included(group_task_id, task_id) values (2, 20);

-- SubTask table
insert into sub_task (task_id, title, is_completed) values (3, 'Wendall', true);
insert into sub_task (task_id, title, is_completed) values (5, 'Tanny', true);
insert into sub_task (task_id, title, is_completed) values (2, 'Casar', true);
insert into sub_task (task_id, title, is_completed) values (3, 'Carr', true);
insert into sub_task (task_id, title, is_completed) values (4, 'Elwin', false);
insert into sub_task (task_id, title, is_completed) values (2, 'Brock', true);
insert into sub_task (task_id, title, is_completed) values (5, 'Abeu', false);
insert into sub_task (task_id, title, is_completed) values (5, 'Jacques', false);
insert into sub_task (task_id, title, is_completed) values (4, 'Nolly', false);
insert into sub_task (task_id, title, is_completed) values (2, 'Stephen', true);
insert into sub_task (task_id, title, is_completed) values (1, 'Hans', true);
insert into sub_task (task_id, title, is_completed) values (4, 'Claire', true);
insert into sub_task (task_id, title, is_completed) values (5, 'Onfre', false);
insert into sub_task (task_id, title, is_completed) values (4, 'Gustav', false);
insert into sub_task (task_id, title, is_completed) values (3, 'Talbot', true);
insert into sub_task (task_id, title, is_completed) values (2, 'Rochester', false);
insert into sub_task (task_id, title, is_completed) values (1, 'Travis', false);
insert into sub_task (task_id, title, is_completed) values (4, 'Shalom', false);
insert into sub_task (task_id, title, is_completed) values (1, 'Hillery', false);
insert into sub_task (task_id, title, is_completed) values (2, 'Lorant', true);

-- Voice table
insert into voice (task_id, name, file) values (7, 'Daisi', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (5, 'Jermaine', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (4, 'Pooh', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (6, 'Shaylyn', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (3, 'Verene', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (5, 'Novelia', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (5, 'Linzy', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (6, 'Ellen', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (7, 'Moyna', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (7, 'Lusa', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (3, 'Cahra', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (3, 'Shaylyn', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (3, 'Celesta', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (7, 'Raven', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (4, 'Elena', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (6, 'Helga', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (7, 'Janaye', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (4, 'Cindra', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (3, 'Kally', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');
insert into voice (task_id, name, file) values (5, 'Ashien', 'https://study4.com/media/tez_media1/sound/ets_toeic_2022_test_1_1.mp3');